//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace selenium_gui_winform {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("selenium_gui_winform.res", typeof(res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project powered by K-Shield Jr. A-09 team\nCopy left all right for you :).
        /// </summary>
        public static string aboutMessage {
            get {
                return ResourceManager.GetString("aboutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selenium SQLi Dector.
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string btnStart {
            get {
                return ResourceManager.GetString("btnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string btnStop {
            get {
                return ResourceManager.GetString("btnStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        public static string cbSave {
            get {
                return ResourceManager.GetString("cbSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully change language to English.
        /// </summary>
        public static string changeLang {
            get {
                return ResourceManager.GetString("changeLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully done! But, failed to open output directory. Because it located on access denied path with application&apos;s permission..
        /// </summary>
        public static string doneCrawl {
            get {
                return ResourceManager.GetString("doneCrawl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Path:.
        /// </summary>
        public static string downPath {
            get {
                return ResourceManager.GetString("downPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Browser.
        /// </summary>
        public static string groupBrowser {
            get {
                return ResourceManager.GetString("groupBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string information {
            get {
                return ResourceManager.GetString("information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string itemAbout {
            get {
                return ResourceManager.GetString("itemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string itemExit {
            get {
                return ResourceManager.GetString("itemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check update.
        /// </summary>
        public static string itemVersion {
            get {
                return ResourceManager.GetString("itemVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string labelTarget {
            get {
                return ResourceManager.GetString("labelTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execite file not found. Start downloading.
        /// </summary>
        public static string notFoundExecute {
            get {
                return ResourceManager.GetString("notFoundExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        public static string stripFile {
            get {
                return ResourceManager.GetString("stripFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        public static string stripHelp {
            get {
                return ResourceManager.GetString("stripHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Language.
        /// </summary>
        public static string stripLang {
            get {
                return ResourceManager.GetString("stripLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read version information at online. Please check your internet connection or contact to your network management team..
        /// </summary>
        public static string updateFail {
            get {
                return ResourceManager.GetString("updateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found new version. Do you want to update?.
        /// </summary>
        public static string updateNew {
            get {
                return ResourceManager.GetString("updateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version is up-to-date..
        /// </summary>
        public static string updateNoNeed {
            get {
                return ResourceManager.GetString("updateNoNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting process. Please wait for end..
        /// </summary>
        public static string waitForEnd {
            get {
                return ResourceManager.GetString("waitForEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;s web driver not found. Please download web driver for your browser!.
        /// </summary>
        public static string webNo {
            get {
                return ResourceManager.GetString("webNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Path: .
        /// </summary>
        public static string webPath {
            get {
                return ResourceManager.GetString("webPath", resourceCulture);
            }
        }
    }
}
