//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace selenium_gui_winform {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class res_ko {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res_ko() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("selenium_gui_winform.res.ko", typeof(res_ko).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 본 프로젝트는 K-Shield Jr.에 의해 제작 되었습니다.\nCopyleft K-Shield Jr. All left reserved for you :).
        /// </summary>
        public static string aboutMessage {
            get {
                return ResourceManager.GetString("aboutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selenium SQLi Detector.
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 닫기.
        /// </summary>
        public static string btn_Exit {
            get {
                return ResourceManager.GetString("btn_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .txt로 저장.
        /// </summary>
        public static string btn_SaveAs {
            get {
                return ResourceManager.GetString("btn_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 시작.
        /// </summary>
        public static string btnStart {
            get {
                return ResourceManager.GetString("btnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 중지.
        /// </summary>
        public static string btnStop {
            get {
                return ResourceManager.GetString("btnStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 설정 저장하기.
        /// </summary>
        public static string cbSave {
            get {
                return ResourceManager.GetString("cbSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 언어를 한국어로 바꾸었습니다..
        /// </summary>
        public static string changeLang {
            get {
                return ResourceManager.GetString("changeLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 작업 중에는 언어를 바꿀 수 없습니다! 잠시 후 다시 시도 해 주십시오..
        /// </summary>
        public static string chgLangWhile {
            get {
                return ResourceManager.GetString("chgLangWhile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 현재 버전: .
        /// </summary>
        public static string currentVersion {
            get {
                return ResourceManager.GetString("currentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 성공적으로 마쳤습니다! 단, 출력 폴더가 권한 상 접근 불가능한 곳에 위치하여 폴더 열기에 실패 하였습니다..
        /// </summary>
        public static string doneCrawl {
            get {
                return ResourceManager.GetString("doneCrawl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 저장 경로:.
        /// </summary>
        public static string downPath {
            get {
                return ResourceManager.GetString("downPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 오류.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 자세한 정보.
        /// </summary>
        public static string gb_Deatil {
            get {
                return ResourceManager.GetString("gb_Deatil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 브라우저 선택.
        /// </summary>
        public static string groupBrowser {
            get {
                return ResourceManager.GetString("groupBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 정보.
        /// </summary>
        public static string information {
            get {
                return ResourceManager.GetString("information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string itemAbout {
            get {
                return ResourceManager.GetString("itemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 종료.
        /// </summary>
        public static string itemExit {
            get {
                return ResourceManager.GetString("itemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 스크립트 업데이트 확인.
        /// </summary>
        public static string itemVersion {
            get {
                return ResourceManager.GetString("itemVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 앱 업데이트 확인.
        /// </summary>
        public static string itemVersionGUI {
            get {
                return ResourceManager.GetString("itemVersionGUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 대상.
        /// </summary>
        public static string labelTarget {
            get {
                return ResourceManager.GetString("labelTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 찾은 포인트.
        /// </summary>
        public static string lbl_CountOfDetect {
            get {
                return ResourceManager.GetString("lbl_CountOfDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 찾은 페이지.
        /// </summary>
        public static string lbl_CountOfScan {
            get {
                return ResourceManager.GetString("lbl_CountOfScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 보고 상태.
        /// </summary>
        public static string lbl_Status {
            get {
                return ResourceManager.GetString("lbl_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 대상.
        /// </summary>
        public static string lbl_Target {
            get {
                return ResourceManager.GetString("lbl_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLi에 대해 더 알아보기.
        /// </summary>
        public static string link_ReadMore {
            get {
                return ResourceManager.GetString("link_ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 새 버전: .
        /// </summary>
        public static string newVersion {
            get {
                return ResourceManager.GetString("newVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 실행 파일을 찾을 수 없습니다. 다운로드를 시작 합니다..
        /// </summary>
        public static string notFoundExecute {
            get {
                return ResourceManager.GetString("notFoundExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pip 모듈 &apos;selenium&apos;을 찾을 수 없습니다. PATH에 등록된 python으로 다운로드를 시작 합니다..
        /// </summary>
        public static string seleniumNotFound {
            get {
                return ResourceManager.GetString("seleniumNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 취약 지점 발견.
        /// </summary>
        public static string status_Found {
            get {
                return ResourceManager.GetString("status_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 취약한 포인트를 찾지 못함.
        /// </summary>
        public static string status_NotFound {
            get {
                return ResourceManager.GetString("status_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 최종 검진 보고서.
        /// </summary>
        public static string string_EndScanReport {
            get {
                return ResourceManager.GetString("string_EndScanReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 보고서를 닫으시겠습니까? 아직 저장되지 않았습니다..
        /// </summary>
        public static string string_NotSave {
            get {
                return ResourceManager.GetString("string_NotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 파일 (&amp;F).
        /// </summary>
        public static string stripFile {
            get {
                return ResourceManager.GetString("stripFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 도움말 (&amp;H).
        /// </summary>
        public static string stripHelp {
            get {
                return ResourceManager.GetString("stripHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 언어 (&amp;L).
        /// </summary>
        public static string stripLang {
            get {
                return ResourceManager.GetString("stripLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 온라인에서 버전 정보를 가져오는데 실패 했습니다. 인터넷 연결을 확인 하거나 네트워크 매니저 팀에게 연락하십시오..
        /// </summary>
        public static string updateFail {
            get {
                return ResourceManager.GetString("updateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 새 버전을 찾았습니다. 다운로드 하시겠습니까?.
        /// </summary>
        public static string updateNew {
            get {
                return ResourceManager.GetString("updateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 최신 버전을 사용 중 입니다..
        /// </summary>
        public static string updateNoNeed {
            get {
                return ResourceManager.GetString("updateNoNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 프로세스를 시작 합니다. 잠시 기다려 주십시오..
        /// </summary>
        public static string waitForEnd {
            get {
                return ResourceManager.GetString("waitForEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 의 웹 드라이버를 찾을 수 없습니다. 브라우저에 맞는 웹 드라이버를 다운로드 해주십시오!.
        /// </summary>
        public static string webNo {
            get {
                return ResourceManager.GetString("webNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;예&apos;를 클릭 하는 경우 기본 브라우저로 다운로드 페이지를 엽니다..
        /// </summary>
        public static string webOpen {
            get {
                return ResourceManager.GetString("webOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 다운로드 경로: .
        /// </summary>
        public static string webPath {
            get {
                return ResourceManager.GetString("webPath", resourceCulture);
            }
        }
    }
}
